// ============================================================================
// Generated file - DO NOT EDIT
// This file is generated by the Flutter localization generator.
// ============================================================================

/// Header for generated localization files.
const String kAppLocalizationHeader = '''
// ============================================================================
// WARNING: This file is generated by Flutter's localization generator.
// DO NOT EDIT THIS FILE DIRECTLY.
// Instead, edit the corresponding ARB file in the l10n/ directory.
// ============================================================================
''';
