// Mocks generated by Mockito 5.4.6 from annotations
// in happy_flutter/test/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:happy_flutter/core/api/api_client.dart' as _i4;
import 'package:happy_flutter/core/encryption/encryption_manager.dart' as _i3;
import 'package:happy_flutter/core/services/encryption_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncryption_1 extends _i1.SmartFake implements _i3.Encryption {
  _FakeEncryption_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setSuspended(bool? suspended) => super.noSuchMethod(
    Invocation.method(#setSuspended, [suspended]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initialize({required String? serverUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#serverUrl: serverUrl}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshServerUrl() =>
      (super.noSuchMethod(
            Invocation.method(#refreshServerUrl, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void updateToken(String? token) => super.noSuchMethod(
    Invocation.method(#updateToken, [token]),
    returnValueForMissingStub: null,
  );

  @override
  void clearToken() => super.noSuchMethod(
    Invocation.method(#clearToken, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {#queryParameters: queryParameters, #options: options},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {#queryParameters: queryParameters, #options: options},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> post(
    String? path, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [path], {#data: data, #options: options}),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> put(
    String? path, {
    dynamic data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [path], {#data: data, #options: options}),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {#data: data, #options: options},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> delete(
    String? path, {
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [path], {#options: options}),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(#delete, [path], {#options: options}),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> uploadFile(
    String? path,
    String? filePath, {
    _i2.ProgressCallback? onSendProgress,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path, filePath],
              {#onSendProgress: onSendProgress, #cancelToken: cancelToken},
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, filePath],
                  {#onSendProgress: onSendProgress, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> downloadFile(
    String? urlPath,
    String? savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #downloadFile,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  bool isAuthError(_i2.Response<dynamic>? response) =>
      (super.noSuchMethod(
            Invocation.method(#isAuthError, [response]),
            returnValue: false,
          )
          as bool);

  @override
  bool isSuccess(_i2.Response<dynamic>? response) =>
      (super.noSuchMethod(
            Invocation.method(#isSuccess, [response]),
            returnValue: false,
          )
          as bool);

  @override
  void clearCache(String? pathPattern) => super.noSuchMethod(
    Invocation.method(#clearCache, [pathPattern]),
    returnValueForMissingStub: null,
  );

  @override
  void clearAllCache() => super.noSuchMethod(
    Invocation.method(#clearAllCache, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, int> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  void debugSeedCache(_i2.Response<dynamic>? response) => super.noSuchMethod(
    Invocation.method(#debugSeedCache, [response]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i6.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Encryption get encryption =>
      (super.noSuchMethod(
            Invocation.getter(#encryption),
            returnValue: _FakeEncryption_1(
              this,
              Invocation.getter(#encryption),
            ),
          )
          as _i3.Encryption);

  @override
  String get anonId =>
      (super.noSuchMethod(
            Invocation.getter(#anonId),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#anonId),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize(_i8.Uint8List? masterSecret) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [masterSecret]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> encryptRaw(dynamic data) =>
      (super.noSuchMethod(
            Invocation.method(#encryptRaw, [data]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#encryptRaw, [data]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<dynamic> decryptRaw(String? encrypted) =>
      (super.noSuchMethod(
            Invocation.method(#decryptRaw, [encrypted]),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i8.Uint8List?> decryptSecretBox(_i8.Uint8List? encryptedData) =>
      (super.noSuchMethod(
            Invocation.method(#decryptSecretBox, [encryptedData]),
            returnValue: _i5.Future<_i8.Uint8List?>.value(),
          )
          as _i5.Future<_i8.Uint8List?>);

  @override
  _i8.Uint8List randomBytes(int? length) =>
      (super.noSuchMethod(
            Invocation.method(#randomBytes, [length]),
            returnValue: _i8.Uint8List(0),
          )
          as _i8.Uint8List);
}
