// Native platform Sentry initialization
import 'package:flutter/foundation.dart'
    show kDebugMode, kReleaseMode;
import 'package:flutter/services.dart' show rootBundle;
import 'package:sentry_flutter/sentry_flutter.dart';

/// Build the Sentry release string.  The version.json file is
/// generated at build time and bundled in assets; if it's missing
/// (local dev) we fall back to a hard-coded value.
Future<String> _sentryRelease() async {
  // CI injects the build number via --build-number.  Flutter
  // writes it into version.json for us automatically, but that
  // file isn't always available (e.g. `flutter run` without
  // --build-number).  Read it from the package info instead:
  // PackageInfo is async and needs platform channels, so we
  // keep a simple fallback.
  const fallback = 'happy_flutter@1.0.0+1';
  try {
    // version.json is generated by `flutter build`
    final json = await rootBundle.loadString(
      'version.json',
      cache: false,
    );
    // e.g. {"app_name":"happy_flutter","version":"1.0.0",
    //        "build_number":"37101", ...}
    final match = RegExp(r'"build_number"\s*:\s*"(\d+)"')
        .firstMatch(json);
    if (match != null) {
      return 'happy_flutter@1.0.0+${match.group(1)}';
    }
  } catch (_) {
    // Not available — use fallback.
  }
  return fallback;
}

Future<void> initSentryForPlatform(
  Future<void> Function() appRunner,
) async {
  final release = await _sentryRelease();

  await SentryFlutter.init(
    (options) {
      options.dsn =
          'https://b4bcb97417717a4e933c1ccb8305d6ab'
          '@o4506225548853248.ingest.us.sentry.io'
          '/4510912147292160';
      options.sendDefaultPii = true;
      options.tracesSampleRate = kReleaseMode ? 0.2 : 1.0;
      options.release = release;
      options.environment =
          kReleaseMode ? 'production' : 'debug';

      // ── ANR detection ──
      options.anrEnabled = true;
      options.anrTimeoutInterval =
          const Duration(seconds: 5);

      // ── Breadcrumb limits ──
      // Increase from default 100 so fetchMessages page
      // breadcrumbs survive until the ANR event is created.
      options.maxBreadcrumbs = 250;

      // ── Attach screenshots on errors/ANRs ──
      options.attachScreenshot = true;

      // Print Sentry diagnostics to console in debug builds
      // so we can verify events are actually being sent.
      options.debug = kDebugMode;
    },
    appRunner: appRunner,
  );
}
